config/routes.rb
Rails.application.routes.draw do
    
  devise_for :users
  get 'persons/profile', as: 'user_root'

    resources :articles do
      resources :comments do
        post 'approve', action: 'approve'
      end
    end
    


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    has_many :comments, dependent: :destroy
    validates :title, presence: true, length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user
  
  enum status: [ :unapproved, :approved ]

  after_create :approved!, if: 'self.article.user == self.user'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :comments
  has_many :articles
  
  # update, edit, destroy
  def owner?(resource)
    self.articles.include?(resource) || self.comments.include?(resource)
  end
  
  def can?(comment)
  self.comments.include?(comment) || self.articles.include?(comment.article)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :authenticate_user!, :except => [:index]
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :check_ability, only: [:edit, :update, :destroy]

    def index
        @articles = Article.all
    end

    def show
    end

    def new
      @article = Article.new
    end

    def edit
    end

    def create
        @article = Article.new(article_params)
        @article.user_id = current_user.id
        if @article.save
        redirect_to @article
        else
          render 'new'
        end
        
    end
    
    def update
      if @article.update(article_params)
        redirect_to @article
      else
        render 'edit'
      end
    end

    def destroy
      @article.destroy

      redirect_to articles_path
    end

    private
    def article_params
        params.require(:article).permit(:title, :text, :user_id)
    end
    
    def check_ability
      raise "you cant do it!" unless current_user.owner? @article
    end
    
    def set_article
      @article = Article.find(params['id'])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :check_destroy_ability, only: [:destroy]

    def create
        @article = Article.find(params['article_id'])
        @comment = @article.comments.new(comment_params)
        @comment.user = current_user
        if @article.save
          redirect_to @article
        else
          render 'new'
        end
    end

    def destroy
        @article = Article.find(params['article_id'])
        @comment = @article.comments.find(params['id'])
        @comment.destroy
        redirect_to article_path(@article)
    end
    
    def approve
        comment = Comment.find(params[:comment_id])
        raise "you cant do it!" unless comment.article.user == current_user
        comment.update(approved:true)
        redirect_to comment.article
    end

    private
    def comment_params
        params.require(:comment).permit(:body)
    end
    
    def check_destroy_ability
    end
end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController
  def profile
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_comments.html.erb
<% if current_user == @article.user %>
<h2>Comments</h2>
<%= render @article.comments %>
<% else %>
<%= render @article.comments.approved %>
<% end %>

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <p>
  Article Author: <%= current_user.email %>
  </p>

  <p>
    <%= f.label :title %> <br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %> <br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to  "Back", articles_path %>

app/views/articles/_table.html.erb
<table>
    <tr>
        <th>Title</th>
        <th>Text</th>
        <th>Comments count</th>
        <th>user_id</th>
    </tr>

    <% @articles.each do |article| %>
        <tr>
            <td>
                <%= article.title %>
            </td>
            <td>
                <%= article.text %>
            </td>
            <td>
                <%= article.comments.count %>
            </td>
            <td>
                <%= article.user_id %>
            </td>
            <td>
                <%= link_to  "Show", article_path(article) %>
            </td>
            <% if current_user&.owner?(article) %>
            <td>
                <%= link_to "Edit", edit_article_path(article) %>
            </td>
            <td>
                <%= link_to "Destroy", article_path(article),
                    method: :delete,
                    data: { confirm: 'Are you sure?' } %>
            </td>
            <% end %>
        </tr>
    <% end %>
</table>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>


  

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<%= link_to 'New article', new_article_path %>

<%= render 'table'%>

<%= link_to 'Index', controller: 'welcome' %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>


app/views/articles/show.html.erb
<p>
    <strong>Title:</strong>
    <%= @article.title %>
</p>

<p>
    <strong>Text:</strong>
    <%= @article.text %>
</p>

<%= render 'comments' %>


<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<% if current_user.owner?(@article) %>
<%= link_to 'Edit', edit_article_path(@article) %> |
<% end %>
<%= link_to 'Back', articles_path %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.user.email %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>
<% if current_user.owner?(comment.article) && comment.unapproved? %>
<%= link_to 'Approve', article_comment_approve_path(comment_id: comment.id, article_id: comment.article.id),
              method: :approve,
              data: { confirm: 'Do you approve this comment?' } %>
<% elsif current_user.can?(comment)%>
<p>
  <%= link_to 'Destroy Comment', [comment.article, comment],
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
</p>
<% end %>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %> <br>
    <%= current_user.email %>
  </p>
  <p>
    <%= f.label :body %> <br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Neblog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <p class="notice"><%= notice %></p>                                                            
  <p class="alert"><%= alert %></p>  
    <%= yield %>
  </body>
</html>

app/views/persons/profile.html.erb
<h1>Persons#profile</h1>
<p>Find me in app/views/persons/profile.html.erb</p>

app/views/welcome/index.html.erb
<% if user_signed_in? %>
    <h1>Hello, <%= current_user.email %></h1>
    <%= link_to 'Выйти', destroy_user_session_path, :method => :delete %>
<% else %>
    <%= link_to 'Войти', new_user_session_path %> или <%= link_to 'Зарегистрироваться', new_user_registration_path %>
<% end %>
<%= link_to  "My Blog", controller: 'articles' %>